<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ris</string>
	</array>
	<key>name</key>
	<string>ReactiveIS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\/\*\*</string>
			<key>end</key>
			<string>\*\*\/</string>
			<key>name</key>
			<string>comment.block.ris</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\/\/.*</string>
			<key>name</key>
			<string>comment.line.ris</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(Wait|Event)</string>
			<key>name</key>
			<string>entity.name.function.ris</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\&amp;|\|)</string>
			<key>name</key>
			<string>support.function.ris</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.ris</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\d+(\.\d+)?|INF)</string>
			<key>name</key>
			<string>constant.numeric.ris</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ris</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ris</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(Texture|Structure)\s+(\S+)\s*=\s*{</string>
			<key>name</key>
			<string>meta.ris</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ris</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(_start\.cond_|_stop\.cond_|_start\.msg_|_stop\.msg_)\s*=</string>
			<key>name</key>
			<string>meta.ris</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ris</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ris</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(Start|End)\s*\((\S*)\)</string>
			<key>name</key>
			<string>meta.ris</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ris</string>
	<key>uuid</key>
	<string>86bd6b97-3c91-4b0e-b66f-7eb175bcc5ea</string>
</dict>
</plist>
